"""empty message

Revision ID: 1f20500a6eac
Revises: f6e75e980162
Create Date: 2026-01-28 01:01:14.210974
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "1f20500a6eac"
down_revision: str | None = "f6e75e980162"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("idx_fact_workouts_src_id_date_workout_set_exercise"), table_name="fact_workouts", schema="bl_3nf"
    )
    op.drop_table("fact_workouts", schema="bl_3nf")
    op.add_column(
        "fact_workouts",
        sa.Column("laterality", sa.VARCHAR(length=255), server_default="Bilateral", nullable=False),
        schema="core",
    )
    op.alter_column(
        "fact_workouts",
        "workout_id",
        existing_type=sa.INTEGER(),
        comment="Unique workout identifier",
        existing_nullable=False,
        autoincrement=True,
        schema="core",
    )
    op.alter_column(
        "fact_workouts",
        "set_type",
        existing_type=sa.TEXT(),
        type_=sa.VARCHAR(length=255),
        existing_nullable=False,
        existing_server_default=sa.text("'Working set'::text"),
        schema="core",
    )
    op.drop_index(op.f("ix_core_fact_workouts_date_id"), table_name="fact_workouts", schema="core")
    op.drop_index(op.f("ix_core_fact_workouts_user_id"), table_name="fact_workouts", schema="core")
    op.drop_constraint(op.f("fact_workouts_equipment_id_fkey"), "fact_workouts", schema="core", type_="foreignkey")
    op.drop_constraint(op.f("fact_workouts_attachment_id_fkey"), "fact_workouts", schema="core", type_="foreignkey")
    op.drop_constraint(op.f("fact_workouts_date_id_fkey"), "fact_workouts", schema="core", type_="foreignkey")
    op.drop_constraint(op.f("fact_workouts_exercise_id_fkey"), "fact_workouts", schema="core", type_="foreignkey")
    op.create_foreign_key(
        None,
        "fact_workouts",
        "dim_attachments",
        ["attachment_id"],
        ["attachment_id"],
        source_schema="core",
        referent_schema="core",
    )
    op.create_foreign_key(
        None,
        "fact_workouts",
        "dim_exercises",
        ["exercise_id"],
        ["exercise_id"],
        source_schema="core",
        referent_schema="core",
    )
    op.create_foreign_key(
        None,
        "fact_workouts",
        "dim_equipment",
        ["equipment_id"],
        ["equipment_id"],
        source_schema="core",
        referent_schema="core",
    )
    op.create_foreign_key(
        None, "fact_workouts", "dim_calendar", ["date_id"], ["date_id"], source_schema="core", referent_schema="core"
    )
    op.create_foreign_key(
        None,
        "fact_workouts",
        "authentication_user",
        ["user_id"],
        ["id"],
        source_schema="core",
        referent_schema="public",
    )
    op.create_table_comment(
        "fact_workouts", "Fact table where users log their workouts.", existing_comment=None, schema="core"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table_comment("fact_workouts", existing_comment="Fact table where users log their workouts.", schema="core")
    op.drop_constraint(None, "fact_workouts", schema="core", type_="foreignkey")
    op.drop_constraint(None, "fact_workouts", schema="core", type_="foreignkey")
    op.drop_constraint(None, "fact_workouts", schema="core", type_="foreignkey")
    op.drop_constraint(None, "fact_workouts", schema="core", type_="foreignkey")
    op.drop_constraint(None, "fact_workouts", schema="core", type_="foreignkey")
    op.create_foreign_key(
        op.f("fact_workouts_exercise_id_fkey"),
        "fact_workouts",
        "dim_exercises",
        ["exercise_id"],
        ["exercise_id"],
        source_schema="core",
        referent_schema="core",
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        op.f("fact_workouts_date_id_fkey"),
        "fact_workouts",
        "dim_calendar",
        ["date_id"],
        ["date_id"],
        source_schema="core",
        referent_schema="core",
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        op.f("fact_workouts_attachment_id_fkey"),
        "fact_workouts",
        "dim_attachments",
        ["attachment_id"],
        ["attachment_id"],
        source_schema="core",
        referent_schema="core",
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        op.f("fact_workouts_equipment_id_fkey"),
        "fact_workouts",
        "dim_equipment",
        ["equipment_id"],
        ["equipment_id"],
        source_schema="core",
        referent_schema="core",
        ondelete="CASCADE",
    )
    op.create_index(op.f("ix_core_fact_workouts_user_id"), "fact_workouts", ["user_id"], unique=False, schema="core")
    op.create_index(op.f("ix_core_fact_workouts_date_id"), "fact_workouts", ["date_id"], unique=False, schema="core")
    op.alter_column(
        "fact_workouts",
        "set_type",
        existing_type=sa.VARCHAR(length=255),
        type_=sa.TEXT(),
        existing_nullable=False,
        existing_server_default=sa.text("'Working set'::text"),
        schema="core",
    )
    op.alter_column(
        "fact_workouts",
        "workout_id",
        existing_type=sa.INTEGER(),
        comment=None,
        existing_comment="Unique workout identifier",
        existing_nullable=False,
        autoincrement=True,
        schema="core",
    )
    op.drop_column("fact_workouts", "laterality", schema="core")
    op.create_table(
        "fact_workouts",
        sa.Column("id", sa.BIGINT(), autoincrement=False, nullable=False),
        sa.Column("src_id", sa.VARCHAR(length=10), autoincrement=False, nullable=False),
        sa.Column("workout_number", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("date_id", sa.DATE(), autoincrement=False, nullable=False),
        sa.Column("set_number", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("exercise_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("reps", sa.NUMERIC(), autoincrement=False, nullable=False),
        sa.Column("load", sa.NUMERIC(), autoincrement=False, nullable=False),
        sa.Column("unit", sa.VARCHAR(length=3), autoincrement=False, nullable=False),
        sa.Column("resistance_id", sa.BIGINT(), autoincrement=False, nullable=False),
        sa.Column("set_type", sa.VARCHAR(length=20), autoincrement=False, nullable=False),
        sa.Column("comments", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("workout_type", sa.VARCHAR(length=10), autoincrement=False, nullable=False),
        sa.Column("ta_created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(["date_id"], ["bl_3nf.ce_dates.DATE"], name=op.f("fk_workouts_dates")),
        sa.ForeignKeyConstraint(
            ["exercise_id"], ["bl_3nf.ce_exercises.exercise_id"], name=op.f("fk_workouts_exercise")
        ),
        sa.ForeignKeyConstraint(
            ["resistance_id"], ["bl_3nf.ce_resistance_types.resistance_id"], name=op.f("fk_workouts_resistance")
        ),
        sa.PrimaryKeyConstraint(
            "id", "date_id", "set_number", "workout_number", "exercise_id", name=op.f("fact_workouts_pkey")
        ),
        sa.UniqueConstraint(
            "src_id",
            "date_id",
            "workout_number",
            "set_number",
            "exercise_id",
            name=op.f("fact_workouts_src_id_date_id_workout_number_set_number_exer_key"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
        schema="bl_3nf",
    )
    op.create_index(
        op.f("idx_fact_workouts_src_id_date_workout_set_exercise"),
        "fact_workouts",
        ["src_id", "date_id", "workout_number", "set_number", "exercise_id"],
        unique=True,
        schema="bl_3nf",
    )
    # ### end Alembic commands ###
