"""empty message

Revision ID: f6e75e980162
Revises: 005
Create Date: 2026-01-27 23:54:08.201673
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f6e75e980162"
down_revision: str | None = "005"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # Check if table already exists (may have been created manually)
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    tables = inspector.get_table_names(schema="core")

    if "fact_workouts" not in tables:
        # ### commands auto generated by Alembic - please adjust! ###
        op.create_table(
            "fact_workouts",
            sa.Column("workout_id", sa.INTEGER(), nullable=False, comment="Unique workout identifier"),
            sa.Column("user_id", sa.INTEGER(), nullable=False),
            sa.Column("workout_number", sa.INTEGER(), nullable=False),
            sa.Column("date_id", sa.DATE(), nullable=False),
            sa.Column("exercise_id", sa.INTEGER(), nullable=False),
            sa.Column("set_number", sa.SMALLINT(), nullable=False),
            sa.Column("repetitions", sa.SMALLINT(), nullable=False),
            sa.Column("load", sa.NUMERIC(), nullable=False),
            sa.Column("unit", sa.TEXT(), server_default="KG", nullable=False),
            sa.Column("equipment_id", sa.INTEGER(), nullable=False),
            sa.Column("attachment_id", sa.INTEGER(), nullable=False),
            sa.Column("set_type", sa.VARCHAR(length=255), server_default="Working set", nullable=False),
            sa.Column("comments", sa.TEXT(), server_default="N/A", nullable=False),
            sa.Column("workout_split", sa.TEXT(), nullable=False),
            sa.Column("ta_created_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
            sa.Column("ta_updated_at", sa.TIMESTAMP(timezone=True), nullable=True),
            sa.ForeignKeyConstraint(
                ["attachment_id"],
                ["core.dim_attachments.attachment_id"],
            ),
            sa.ForeignKeyConstraint(
                ["date_id"],
                ["core.dim_calendar.date_id"],
            ),
            sa.ForeignKeyConstraint(
                ["equipment_id"],
                ["core.dim_equipment.equipment_id"],
            ),
            sa.ForeignKeyConstraint(
                ["exercise_id"],
                ["core.dim_exercises.exercise_id"],
            ),
            sa.ForeignKeyConstraint(
                ["user_id"],
                ["public.authentication_user.id"],
            ),
            sa.PrimaryKeyConstraint("workout_id"),
            schema="core",
            comment="Fact table where users log their workouts.",
        )

    # Check if indexes exist before creating them
    indexes = inspector.get_indexes("fact_workouts", schema="core")
    index_names = [idx["name"] for idx in indexes]

    if "ix_fact_workout_user_date" not in index_names:
        op.create_index(
            "ix_fact_workout_user_date", "fact_workouts", ["user_id", "date_id"], unique=False, schema="core"
        )
    if "ix_fact_workout_user_id" not in index_names:
        op.create_index("ix_fact_workout_user_id", "fact_workouts", ["user_id"], unique=False, schema="core")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_fact_workout_user_id", table_name="fact_workouts", schema="core")
    op.drop_index("ix_fact_workout_user_date", table_name="fact_workouts", schema="core")
    op.drop_table("fact_workouts", schema="core")
    # ### end Alembic commands ###
