"""Shared backend constants for workouts, dimensions, and analytics time filters."""

PLACEHOLDER_DIMENSION_ID = -1
PLACEHOLDER_DIMENSION_NAME = "None"

SCENARIO_ACTUALS = "actuals"
SCENARIO_PLAN = "plan"
SCENARIO_CHOICES = (SCENARIO_ACTUALS, SCENARIO_PLAN)

TIME_FILTER_ALL = "all"
TIME_FILTER_WTD = "wtd"
TIME_FILTER_MTD = "mtd"
TIME_FILTER_YTD = "ytd"
TIME_FILTER_CURRENT = (TIME_FILTER_ALL, TIME_FILTER_WTD, TIME_FILTER_MTD, TIME_FILTER_YTD)
