repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.1
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format

  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: uv run mypy
        language: system
        types: [python]
        pass_filenames: false
        args: ["."]
      - id: dbt-compilation
        name: dbt-compilation
        entry: bash -c 'cd db/transformation && uv run dbt compile'
        language: system
        pass_filenames: false 
        files: ^db/transformation/

