# Generated by Django 5.2.7 on 2025-11-04 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='attachments',
            table='attachments',
        ),
        migrations.AlterModelTable(
            name='calendar',
            table='calendar',
        ),
        migrations.AlterModelTable(
            name='equipment',
            table='equipment',
        ),
        migrations.AlterModelTable(
            name='exercise_muscle_bridge',
            table='exercise_muscle_bridge',
        ),
        migrations.AlterModelTable(
            name='exercises',
            table='exercises',
        ),
        migrations.AlterModelTable(
            name='muscles',
            table='muscles',
        ),
        migrations.AlterModelTable(
            name='workouts',
            table='workouts',
        ),
    ]
