# Generated by Django 5.2.7 on 2025-11-04 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_attachments_table_alter_calendar_table_and_more'),
    ]

    operations = [
        migrations.RunSQL("ALTER TABLE public.exercises SET SCHEMA core;"),
        migrations.RunSQL("ALTER TABLE public.workouts SET SCHEMA core;"),
        migrations.RunSQL("ALTER TABLE public.muscles SET SCHEMA core;"),
        migrations.RunSQL("ALTER TABLE public.equipment SET SCHEMA core;"),
        migrations.RunSQL("ALTER TABLE public.attachments SET SCHEMA core;"),
        migrations.RunSQL("ALTER TABLE public.calendar SET SCHEMA core;"),
        migrations.RunSQL("ALTER TABLE public.exercise_muscle_bridge SET SCHEMA core;"),
    ]
