# Generated by Django 5.2.8 on 2025-12-07 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_attachments_ta_updated_at_equipment_ta_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise_muscle_bridge',
            name='muscle_role',
            field=models.TextField(null=True),
        ),
    ]
