# Generated by Django 5.2.8 on 2025-12-07 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_exercise_muscle_bridge_muscle_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise_muscle_bridge',
            name='muscle_role',
            field=models.TextField(default=None, null=True),
        ),
    ]
