# Generated by Django 5.2.8 on 2026-01-22 06:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_alter_exercise_muscle_bridge_muscle_role"),
    ]

    operations = []
