name: 'transformation'
version: '1.0.0'

profile: 'transformation'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

seeds:
  transformation:
    +schema: staging
    seed_exercises:
      +alias: seed_dim_exercises
    seed_muscles:
      +alias: seed_dim_muscles
    seed_equipment:
      +alias: seed_dim_equipment
    seed_attachments:
      +alias: seed_dim_attachments
    seed_exercise_muscle:
      +alias: seed_exercise_muscle_bridge

models:
  transformation:
    +schema: core
    dim_calendar:
      +materialized: table
      +primary_key: date_id
    dim_equipment:
      +materialized: table
      +primary_key: equipment_id
    dim_attachments:
      +materialized: table
      +primary_key: attachment_id
    exercise_muscle_bridge:
      +materialized: table
      +primary_key: id
