name: unit-tests

on: 
  pull_request:
    branches: [main, dev]
    paths:
        - 'backend/**'
        - 'tests/ui/**'
        - 'tests/meta/**'
  push:
    branches: [main, dev]
    paths:
        - 'backend/**'
        - 'tests/ui/**'
        - 'tests/meta/**'

jobs: 
  auth-tests:
    runs-on: ubuntu-latest
    environment: dev
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Install uv
        uses: astral-sh/setup-uv@v4
      
      - name: Set up Python
        run: uv python install 3.12
      
      - name: Install dependencies
        run: uv sync
      
      - name: Run tests
        run: uv run pytest tests/unit/ -v
        env:
          DJANGO_SETTINGS_MODULE: backend.settings
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          DJANGO_DEBUG: "False"
          DJANGO_ALLOWED_HOSTS: "*"
          DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
          MAILERSEND_API_TOKEN: ${{ secrets.MAILERSEND_API_TOKEN }}
          MAILERSEND_FROM_EMAIL: ${{ secrets.MAILERSEND_FROM_EMAIL }}
          FRONTEND_URL: ${{ secrets.FRONTEND_URL }}
          BACKEND_URL: ${{ secrets.BACKEND_URL }}
          UI_TESTER_USERNAME: ${{ secrets.UI_TESTER_USERNAME }}
          UI_TESTER_PASS: ${{ secrets.UI_TESTER_PASS }}

